apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-api
spec:
  selector:
    matchLabels:
      app: student-app-api
  replicas: 1
  template:
    metadata:
      labels:
        app: student-app-api
    spec:
      containers:
        - name: student-app-api
          image: piotrek1992/student-app-api:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME  # Setting Database username from Secret
              value: root
#              valueFrom:
#                secretKeyRef:
#                  name: db-credentials # Secret Name
#                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

#          env:
#            - name: MONGO_URL
#              value: mongodb://mongo:27017/dev
#          env:
#            - name: MONGO_URL
#              valueFrom:
#                configMapKeyRef:
#                  name: student-db-config
#                  key: dbpath

#          env:
#            - name: MONGO_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: mongo-secret
#                  key: username
#            - name: MONGO_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mongo-secret
#                  key: password
#            - name: MONGO_DB
#              valueFrom:
#                configMapKeyRef:
#                  name: mongo-conf
#                  key: database
#            - name: MONGO_HOST
#              valueFrom:
#                configMapKeyRef:
#                  name: mongo-conf
#                  key: host
